### ISSUE TITLE
Client side hmac?

### ISSUE THREAD

**Issue by RWOverdijk** [peralmq/react-adyen-hpp-button#1]
Hey!

I was about to use your component when I noticed you calculate the merchant signature client side. Is that allowed? Doesn't that mean the client can define their own prices?

**Comment by peralmq** [comment]
@RWOverdijk I've used this component to set up Adyen [recurring payments](https://docs.adyen.com/developers/features/recurring-payments). In that case the initial payment isn't important, i.e. could be € 0, but the next payments are.

For your case the situation might be different. But one safeguard could be to look up previous made payment via the `pspReference` that can be found in the [HPP Payment Response](https://docs.adyen.com/developers/features/hosted-payment-pages/hpp-payment-response). I'd recommend that you speak directly with Adyen about such solutions though.

**Comment by RWOverdijk** [comment]
Yeah after looking into it this isn't the plugin for us. It might be a good idea to mention in the README, it's a security risk. Thanks for your reply!
